export const NAV_ITEMS = [
  { href: "/dashboard", labelKey: "home" },
  { href: "/setup", labelKey: "setup" },
  { href: "/esg-summary", labelKey: "esgSummary" },
  { href: "/questionnaire", labelKey: "questionnaire" },
  { href: "/materiality", labelKey: "materiality" },
  { href: "/data-collection", labelKey: "dataCollection" },
  { href: "/emissions", labelKey: "emissions" },
  { href: "/risks", labelKey: "risks" },
  { href: "/targets", labelKey: "targets" },
  { href: "/reports", labelKey: "reports" },
  { href: "/certification", labelKey: "certification" },
  { href: "/audit-trail", labelKey: "auditTrail" },
  { href: "/settings", labelKey: "settings" },
] as const;

export const MATERIALITY_TOPICS = [
  "Climate change",
  "Energy management",
  "Water management",
  "Waste and circular economy",
  "Biodiversity",
  "Occupational health and safety",
  "Labor practices",
  "Human rights",
  "Supply chain responsibility",
  "Business ethics",
  "Data privacy",
  "Community impact",
];
